[package]
name = "htop"
version = "0.1.0"
description = "an interactive process viewer"
homepage = "https://htop.dev"
license = "GPL-2.0"
url = "https://github.com/htop-dev/htop/archive/refs/tags/3.4.1.tar.gz"
depends = []
post_install = "./autogen.sh && ./configure && make && cp htop /usr/local/bin/htop"

[package.files]
